#!/bin/bash
echo "flatpak update -y"
flatpak update -y
echo " " >> $HOME/0_data_atualizado.txt
echo "Flatpak atualizado em:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt
echo "flatpak uninstall --unused -y"
flatpak uninstall --unused -y
echo " " >> $HOME/0_data_atualizado.txt
echo "Limpeza dos runtimes do Flatpak:" >> $HOME/0_data_atualizado.txt
echo $(date) >> $HOME/0_data_atualizado.txt
